# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27e9ef547bb2a9fb7a2ba5daff06200e5d282775b3c62261011708760ed333e160e5a5765e4d6ca17ec6ff4dd6ac0715f0b1815e08f49d7959e38f83f1b54d60

test:
  secret_key_base: d90cd4207b4bd48ac347c52da9e574e2f189713209e9a9e8dd8e6acaceac47d9f333d39542dfb656457e0a2ef97f162f779e81ffb3fbbe68cd6e5fb5eb7217ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
